# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2b302ac
_src_path: gh:blakeNaccarato/copier-python-init
docs_engine: MyST
github_repo_name: captivate
project_email: blake.naccarato+captivate@gmail.com
project_name: captivate
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.11'
year_of_project_creation: 2023
